//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa_depositos
    {
        public empresa_depositos()
        {
            this.compras_detalle = new HashSet<compras_detalle>();
            this.productos_deposito = new HashSet<productos_deposito>();
            this.productos_kardex = new HashSet<productos_kardex>();
            this.productos_movimientos = new HashSet<productos_movimientos>();
            this.productos_movimientos1 = new HashSet<productos_movimientos>();
            this.ventas_detalle = new HashSet<ventas_detalle>();
        }
    
        public string auto { get; set; }
        public string nombre { get; set; }
        public string codigo { get; set; }
    
        public virtual ICollection<compras_detalle> compras_detalle { get; set; }
        public virtual ICollection<productos_deposito> productos_deposito { get; set; }
        public virtual ICollection<productos_kardex> productos_kardex { get; set; }
        public virtual ICollection<productos_movimientos> productos_movimientos { get; set; }
        public virtual ICollection<productos_movimientos> productos_movimientos1 { get; set; }
        public virtual ICollection<ventas_detalle> ventas_detalle { get; set; }
    }
}
