//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMySql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class leonuxEntities : DbContext
    {
        public leonuxEntities()
            : base("name=leonuxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<compras> compras { get; set; }
        public virtual DbSet<empresa_depositos> empresa_depositos { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<productos_deposito> productos_deposito { get; set; }
        public virtual DbSet<productos_movimientos> productos_movimientos { get; set; }
        public virtual DbSet<ventas> ventas { get; set; }
        public virtual DbSet<compras_detalle> compras_detalle { get; set; }
        public virtual DbSet<productos_kardex> productos_kardex { get; set; }
        public virtual DbSet<productos_movimientos_detalle> productos_movimientos_detalle { get; set; }
        public virtual DbSet<ventas_detalle> ventas_detalle { get; set; }
        public virtual DbSet<productos_conceptos> productos_conceptos { get; set; }
    }
}
